# -*- mode: python ; coding: utf-8 -*-

import os

datas = [
    ('index.html', '.'),
    ('styles.css', '.'),
    ('app.js', '.'),
    ('dom.js', '.'),
    ('state.js', '.'),
    ('ui.js', '.'),
    ('registry.js', '.'),
    ('history.js', '.'),
    ('vault.js', '.'),
    ('ciphers.js', '.'),
    ('sw.js', '.'),
    ('logo.png', '.'),
    ('icon.png', '.'),
    ('icon-maskable.png', '.'),
    ('manifest.json', '.'),
    ('lucide.min.js', '.'),
    ('qrcode.js', '.'),
    ('argon2-bundled.min.js', '.'),
    ('argon2-worker.js', '.'),
    ('fonts', 'fonts'),
]

# The public signing certificate is generated by sign_app.ps1; bundle it when
# present so first-run trust prompts work, but don't fail the build without it.
if os.path.exists('AegisRoot.cer'):
    datas.append(('AegisRoot.cer', '.'))

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='BasementenAegis',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
)
